### ISSUE TITLE
Complete connector separation of SharePoint Server from SharePoint Online 

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#1008]
The 8.8 SharePoint Online & Server connector is split in 8.9 in 2 separate connectors.
- [ ] Rename [sharepoint.py](https://github.com/elastic/connectors-python/blob/main/connectors/sources/sharepoint.py) to sharepoint-server.py
- [ ] Adjust references in the code to mention SharePoint Server only.
- [ ] Keep only the configurable fields that are relevant for Server.
- [ ] Update connector client documentation. SharePoint Server connector reaches Beta.

**Comment by akanshi-elastic** [comment]
Started working on this issue on 7th june. As of now the code is raised as draft PR on github for artem's review. Once our QA team verify the changes so we'll open it for review.
