### ISSUE TITLE
disk-based queues

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#1031]
When the backend is very fast, it fills the bulk queue pretty quickly, and then we are slowly sending data via `_bulk` calls and forcing a throttling on the backend. We are only doing this to avoid getting big in memory.

In theory, it's OK to have the backend wait. In practice, it can lead to issues. For instance, when bulk gets very slow, and the backend keeps a cursor for its connection like Mongo, we can lose it if we idle for too long.

A disk-based queue will allow us to grab data as fast as we want from the backend and reduce by a lot our memory usage.

To do this, we need to implement a disk-based queue that follows the same set of APIs as `MemQueue` https://github.com/elastic/connectors-python/blob/main/connectors/utils.py#L194

Pretty simple implementation: the queue uses a directory and drops each document under an auto inc name, 
and keeps the count in memory so we do just one fd lookup to get/write a document. 

Bonus: it's crash safe compared to `MemQueue`

**Comment by seanstory** [comment]
closing as a won't fix. The right solution is to handle backpressure, not to build a bigger queue that has worse consequences when it overflows.
