### ISSUE TITLE
Sync is not getting completed for Jira Cloud & Confluence Cloud connector when checked as a Native Connector.

### ISSUE THREAD

**Issue by khushbu-elastic** [elastic/connectors-python#1045]
## Bug Description
Sync is not getting completed for Jira Cloud & Confluence Cloud connector when checked as a Native Connector.

### To Reproduce

1. Execute the Jira Cloud or Confluence cloud instance as a Native Connector configured with correct values.

## Expected behavior
No Error should be displayed and Jira Cloud Connector & Confluence Cloud Connector should run successfully.

## Actual Result:
The execution for Jira Cloud & Confluence Cloud is not getting completed and sync keeps going for n amount of time. Indexing of all the documents is not happening. The sync execution gets interrupted in between (Shows - In Progress) and gets into the infinite execution.
We have to stop the execution by manual intervention.

## Screenshots
![error for confluence cloud](https://github.com/elastic/connectors-python/assets/133654004/62c252a0-5224-40ea-960f-a92fccb5e970)
![error for confluence cloud1](https://github.com/elastic/connectors-python/assets/133654004/4b636907-bb41-4258-900c-415d96bc79a5)

## Environment
- Elastic Version: Elastic Cloud v8.8.0
- OS: Alma Linux 8
- Browser: Chrome
- Version: Version 113.0.5672.127 (Official Build) (64-bit)

## Additional context
Sync is getting completed for Jira Server & Confluence Server connector when checked as a Native Connector. It is working fine.

**Comment by sphilipse** [comment]
Hi @khusbu-elastic, can you paste the connector document from the `.elastic-connectors` index for this connector?

**Comment by khushbu-elastic** [comment]
@sphilipse I have shared that in the slack DM.

**Comment by sphilipse** [comment]
So in this case the connector has the wrong `status`, which should be set to `configured` after you've added the right connector configuration. I'm not sure if I got that right in the initial document, I'll change and add that if not.

**Comment by khushbu-elastic** [comment]
@sphilipse I have checked this again today with newly created elastic-cloud instance v8.8.0 and it seems Jira & Confluence Cloud connector are working fine as a Native Connector. 
But seems working very slow as Indexing 300 documents taking 384 secs approximately for Confluence cloud and Indexing 4 documents took 72 secs approximately.

But as the functionality for the both the connectors cloud are working fine, closing this issue for now.
