### ISSUE TITLE
Unexpected text extraction failures report non-actionable errors

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors-python#1155]
## Bug Description
When unexpected text extraction error happens, sometimes no error is reported and it's not possible to act on it

### To Reproduce
1. Create a Sharepoint Online connector that will sync all site collections (*)
2. Start a sync and observe logs
3. See error:
```
[FMWK][12:58:32][ERROR] Text extraction unexpectedly failed. Error:
[FMWK][12:58:44][ERROR] Text extraction unexpectedly failed. Error:
```

## Expected behavior
Error is communicated clearly.

**Comment by seanstory** [comment]
@navarone-feekery to confirm if this is still an issue

**Comment by navarone-feekery** [comment]
I confirmed that this is still occurring, I'll investigate.

**Comment by navarone-feekery** [comment]
Actually, I was mistaken -- this doesn't happen anymore.
A similar error was happening, and it also happens when not using local text extraction. When I run a full sync on the enterprise search sites, I occasionally get `Exception found for task Task-5802:` with no actionable information.

**Comment by artem-shelkovnikov** [comment]
@navarone-feekery it can probably be closed now then - there's another issue for the empty "Exception found for task" exception: https://github.com/elastic/connectors-python/issues/789

**Comment by navarone-feekery** [comment]
I did one more sync on the full enterprise search collection and couldn't reproduce (just to quadruple check) and it isn't occurring anymore, so I'll close this.
