### ISSUE TITLE
[Sharepoint Online] Improve performance of Identity Sync

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors-python#1204]
As reported, syncing identities takes a long time:

![image](https://github.com/elastic/connectors-python/assets/12238374/1b1ef41c-bead-44d6-91e7-c3f072a744a8)

Minor triaging showed the following:

We fetch members for each group for each user but instead we can fetch groups and its members with $expand query: https://graph.microsoft.com/v1.0/groups?$expand=members . It can reduce number of calls to Sharepoint dramatically.
Right now the number of calls is gonna be:
For each user (N users)
For each group (M groups per user)
Fetch members, so
N * M - for 300 users and 4 groups each it’s 1200 requests.

For 42000 users in the screenshot and assuming at least 10 groups, it's gonna be 420.000 requests each costing 5 resource units. 

We need to optimize this logic to reduce sync time.

**Comment by seanstory** [comment]
☝️ if that PR's approach goes in, I'll need to also:
- [ ] update the Kibana configuration for Native SPO connectors
- [ ] update the configuration reference for the SPO connector docs

**Comment by seanstory** [comment]
closing this, though https://github.com/elastic/enterprise-search-team/issues/5162 is a follow-up, because this change was insufficient.
