### ISSUE TITLE
Sync Rules: Network Drive, Postgres, MSSQL

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#1290]
Enhance the 3 mentioned connectors with advanced sync rules support.

### Acceptance criteria

- [x] discovery document with advanced sync rules for
    - [x] Network Drive 
    - [x] #1690
    - [x] #1484
- [x] add support for advanced sync rules as defined in the discovery
- [x] documentation with several examples illustrating the syntax, how a basic use case works, limitations
- [ ] document impact of advanced sync rules on connector configuration and on document indexing
- [x] add tooltip on the configurable fields that are ignored when advanced sync rules are used, informing the user about the behavior. Text to be used as tooltip: "This configurable field is ignored when Advanced Sync Rules are used."

**Comment by praveen-elastic** [comment]
Updates: 

- Explored Sync Rules implementation in Network Drives
- Shared a Documentation containing Schema for Sync Rules Object Model

**Comment by praveen-elastic** [comment]
Updates for 21st July to 27th July:

- Network Drive Sync Rules PR is ready to review: https://github.com/elastic/connectors-python/pull/1341

**Comment by parth-elastic** [comment]
Updates for 27 July to 3rd August:

- Kicked off initial implementation with postgres sync rules.

**Comment by parth-elastic** [comment]
Updates for 4th August to 10th August

- Connect with Chunhui about GDC refactoring and finalize the schema for MS-SQL and PostgreSQL.
- Kicked of MS-SQL sync rules as Tim is working on PostgreSQL.

**Comment by parth-elastic** [comment]
Updates for 11 August to 24 August

- Implemented MS-SQL sync rules.
- Raised PR for MS-SQL Sync rules
- Addressed comments for the 1st round of review
- Awaiting rereview from Chenhui

**Comment by parth-elastic** [comment]
Hey @danajuratoni, Sync rules for MS-SQL, Network Drives and PostgreSQL are merged.
Also, documentation for the same is also up to date.

Could you please complete all the checkbox and close the issue if all looks good to you

**Comment by danajuratoni** [comment]
@parth-elastic I updated the checkboxes I could validate.

> document impact of advanced sync rules on connector configuration and on document indexing

Has this been documented anywhere? 
From the code, I see only "Comma-separated list of tables" for MSSQL and Postgres has the mentioned tooltip. Can't the others e.g. database/schema be bypassed like for MySQL?
<img width="569" alt="image" src="https://github.com/elastic/connectors-python/assets/102797748/0f6462c8-8c9d-4cdb-9801-90bb05d40ac5">
cc: @leemthompo @timgrein @wangch079

**Comment by parth-elastic** [comment]
@danajuratoni In PostgreSQL and MS-SQL, users need to configure database and schema in the rich configuration field, and in sync rules, users will configure tables and query only. So, the connector will check if the mentioned tables(in sync rules) are available in the mentioned database and schema (in rich configuration field) or not. So, only tables will be bypass from configuration, not database and schema.

**Comment by danajuratoni** [comment]
>the connector will check if the mentioned tables(in sync rules) are available in the mentioned database and schema (in rich configuration field) or not

@timgrein if I remember correctly this is different than for MySQL, where we don't validate the tables and use advanced rules only when present. 
Can we make sure 
- validation issues are properly logged and
- documentation exists to hightlight this behavior

**Comment by parth-elastic** [comment]
@danajuratoni AFAIK, in MySQL also, we are validating tables. In MySQL, we don't have schema, so the connector will check if configure tables (in sync rules) are present in the configure database (in rich configuration) or not.

cc @timgrein Can confirm once

**Comment by timgrein** [comment]
@parth-elastic I'm not too sure, if we really check the configured tables, but more so the tables, which we find in the remote database, right? See: https://github.com/elastic/connectors-python/blob/main/connectors/sources/mysql.py#L122-L130

**Comment by parth-elastic** [comment]
Yes @timgrein, I am talking about `_remote_validation`. So, we are validating configured tables (in sync rules) in `_remote_validation`. And the comma-separated list of tables (rich configuration field) is bypassed. So, the conclusion is that a database in the rich configuration field is required because we use it in `_remote_validation`.

**Comment by timgrein** [comment]
I see, yes the database is required 👍 Thanks for clarifying

**Comment by parth-elastic** [comment]
Yes, so @danajuratoni we can mention all necessary information in the documentation and close this issue as Tim confirmed the behaviour

**Comment by parth-elastic** [comment]
Sure @leemthompo,  So the conclusion is that in PostgreSQL, MS-SQL, and MySQL, when advanced sync rules are enabled, only `Comma-separated list of tables` will bypass other fields are required.

**Comment by danajuratoni** [comment]
Thanks for confirming!
@leemthompo seems MySQL needs updating too.
Closing this as done, and we'll track documentation separately.
