### ISSUE TITLE
The elastic-ingest command fails for non-native service_type created using 'build a connector' from UI

### ISSUE THREAD

**Issue by praveen-elastic** [elastic/connectors-python#145]
### Problem Description

When running a non-native service_type using build a connector, the connector status is `created`. Hence, the elastic-ingest command fails since the if-condition in runner.py checks whether the connector status is `created`: 

https://github.com/elastic/connectors-python/blob/5ec59cf588e535046ae64cc011b272f90ed0a7f1/connectors/runner.py#L98

![image](https://user-images.githubusercontent.com/90465691/198331819-3600ccc4-8443-40aa-9882-0c967270df7d.png)

**Comment by tarekziade** [comment]
related to https://github.com/elastic/connectors-python/issues/38

**Comment by praveen-elastic** [comment]
Closing the issue since the PR is merged and the patch is working fine.
