### ISSUE TITLE
Confluence Sync has Jobtype.UNSET

### ISSUE THREAD

**Issue by JohannesPertl** [elastic/connectors-python#1528]
## Bug Description
When starting a sync job for the confluence connector, the JobType is UNSET. The job  works if I manually set the JobType to FULL.

### To Reproduce
1. Go to the custom connector index in Kibana
2. Click on 'Sync'
4. See error: Unsupported job type 'JobType.UNSET'. Skipping sync job execution...

## Expected behavior
JobType should be FULL

## Screenshots
![image](https://github.com/elastic/connectors-python/assets/45853628/bcd2be0d-0ebe-4764-b2fc-8c0decb5c848)

**Comment by timgrein** [comment]
Hi @JohannesPertl,

Thank you for opening this issue. Can you provide the used versions of Elasticsearch, Enterprise Search and connectors-python by chance?

**Comment by praveen-elastic** [comment]
@JohannesPertl I think it is fixed in Elastic: 8.9 release. Can you please check it on the 8.9 Elastic deployment ?

**Comment by JohannesPertl** [comment]
@praveen-elastic I just tested it on 8.9.0 and it works :+1:

**Comment by timgrein** [comment]
Closing this issue then, thanks again for raising it @JohannesPertl !
