### ISSUE TITLE
MySQL align BE to reflect "List of MySQL databases" is required

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#171]
## Current behavior
Configured MySQL with the vault data, leaving "List of MySQL databases" empty.
Sync gets triggered, but 0 docs are indexed.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/102797748/198022071-2977c4db-f4dd-4f0e-b4f2-970b9d575949.png">

## Expected behavior
For 8.6 we should align the BE code to reflect that no databases should be sync'd if the parameter "List of MySQL databases" is empty.

## Context
This ticket is a short-/mid- term solution. Long term solution is to add UI option where user should be able to explicitly select that they want to select all databases, this enhancement is dependent on adding support for rich configurable fields in the framework.

[Ref code](https://github.com/elastic/connectors-python/blob/main/connectors/sources/mysql.py#L308-L309)

**Comment by parth-crest** [comment]
@danajuratoni previously we were getting empty list ([]) if user has not passed any value in the "List of MySQL databases" from the UI. Now we are getting empty string ("") which breaks our code. We have refactored our code to work in both cases empty list and empty string and it will fetch all the databases in both the cases.

**Comment by parth-crest** [comment]
Should we change our code to index nothing if user has passed empty value in "List of MySQL databases"?

**Comment by danajuratoni** [comment]
Yes, please adjust the code such that no databases are ingested if the list is empty.

**Comment by parth-crest** [comment]
Sure, we will update that.

**Comment by danajuratoni** [comment]
@parth-crest please update this ticket as soon as the changes as merged via the PR you mention, as that PR is not linked to this ticket.

**Comment by parth-crest** [comment]
@danajuratoni Code is merged to main. We can close this issue.

cc @tarekziade

**Comment by danajuratoni** [comment]
> @danajuratoni Code is merged to main. We can close this issue.
> 
> cc @tarekziade

Closing per comment above
