### ISSUE TITLE
Inform user about MySQL connection errors (e.g. invalid database)

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#185]
If a sync is triggered on a non-existent database don't obfuscate not-found errors. Currently the user does not get any feedback about issues with the connection / possible misconfiguration, and the sync reports 0 documents being indexed. 

## Expected behavior 
Ideally, we should validate that the configuration is correct and inform the user about any possible issues.
Error message should be displayed with the relevant message to guide users stating that chosen database is not available. Ideally, provide list of available databases.

This should be reported in UI in a similar manner to how MongoDB does it
<img width="689" alt="image" src="https://user-images.githubusercontent.com/102797748/201693557-8d2d42d6-b686-41c9-baf6-0d39ee223e7c.png">

**Comment by danajuratoni** [comment]
Note: this in an older screenshot, the ingestion status should be aligned with the work @wangch079 did for 8.6.

**Comment by parth-crest** [comment]
@danajuratoni The mongoDB reference you attached is from Ruby connectors. It looks like we would have to change framework to validate the user config parameters from the UI. Since this is a generic change and not related to the MySQL connector, should Tarek pick this up?

cc @tarekziade

**Comment by danajuratoni** [comment]
@tarekziade I would have expected this logic to be at connector client level, as the UI is already in place(work was done for the ruby framework). Is there something you need to unblock in the framework before @parth-crest is able to work on the connector?

**Comment by tarekziade** [comment]
Any error raised by the connector is bubbling up there so I think we just need to make sure the MySQL raise the error and ensure that the framework does bubble it up. This was working for the framework side

**Comment by artem-shelkovnikov** [comment]
About error handling: both Ruby and Python frameworks are trying to follow the same pattern which is:

If connector faced an error that it wants to communicate to the user, connector should raise an exception with human-readable message.

Message should be short enough, single-line and not contain any internal technical information - stack traces, etc.

If libraries that connector use produce exceptions that are not human-readable, then connector should catch them and re-raise new exception with human-readable error message with original exception included.

If you follow the process above (raising errors from connector) and do not see UI in Kibana change, then it's a bug and we should address it at a framework level

**Comment by parth-crest** [comment]
Ok. We got your point, We'll change our code to raise the error if user has mentioned any inaccessible  databases as @danajuratoni mentioned. Also it will raise the error that says "Can not connect to MySQL server" if any of the required parameters are missing i.e. username, host or password.

**Comment by artem-shelkovnikov** [comment]
> Also it will raise the error that says "Can not connect to MySQL server" if any of the required parameters are missing i.e. username, host or password.

Please make sure to include what is missing in the error message!

**Comment by parth-crest** [comment]
Sure. we'll take care of that too.
