### ISSUE TITLE
Last sync status is not updated in the Elasticsearch index after the sync is completed

### ISSUE THREAD

**Issue by prashant-elastic** [elastic/connectors-python#192]
## Bug Description
Last sync status is not updated in the Elasticsearch index after the sync is completed

### To Reproduce
1. Do the necessary changes in the config file
2. Create an index from the Elasticsearch UI and use a native connector to configure MySQL host details
3. Execute elastic-ingest to index the documents

## Expected behavior
All the documents should be indexed and last sync status should be updated

## Actual behavior
All the documents are indexed correctly but the last sync status is not updated. Please find attached screenshot for reference.

## Screenshots
<img width="1440" alt="Screen Shot 2022-11-16 at 12 47 38 PM" src="https://user-images.githubusercontent.com/103035276/202114279-ddd70e01-889c-434a-9cca-917140a82b46.png">

## Environment
Elasticsearch Cloud instance v8.5.0

- OS: Ubuntu v22.04.1
- Browser - Chrome v107.0.5304.110

**Comment by DianaJourdan** [comment]
@prashant-elastic could you please check if you still manage to reproduce this issue? It should be fixed in the meantime as we have done MySQL validation in 8.7 and did not face it

**Comment by artem-shelkovnikov** [comment]
Tested it and it's not a problem. I'll go ahead and close the issue, feel free to reopen if it's still the case for you @prashant-elastic
