### ISSUE TITLE
Add connector (MySQL) support for custom certificate authority

### ISSUE THREAD

**Issue by serenachou** [elastic/connectors-python#232]
### Problem Description
When deploying an Azure MySQL database, our MySQL connector cannot connect and does not support all of the configuration parameters required.  SSL is required 
<img width="681" alt="image" src="https://user-images.githubusercontent.com/13574083/206553068-e60806a5-d982-4bfa-b10d-0a4818a3e7dd.png">

Example python connection  : 
cnx = mysql.connector.connect(user="{your_user}", password="{your_password}", host="ent-search-mysql.mysql.database.azure.com", port=3306, database="{your_database}", ssl_ca="{ca-cert filename}", ssl_disabled=False)

We need to support all the parameters needed to support customers who want to pull data from: https://learn.microsoft.com/en-us/azure/mysql/flexible-server/connect-azure-cli 

But we only support parameters for username, password, host, port & database. 

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/13574083/206552973-aba7b128-f46d-4b2a-90b9-0e3a6a660030.png">

**Comment by tarekziade** [comment]
Let's make sure the new params are strings, as we can't rely on disk in cloud. (see my remark on the GCS patch)

**Comment by serenachou** [comment]
Added a frontend ticket: https://github.com/elastic/enterprise-search-team/issues/3551
