### ISSUE TITLE
Error on executing elastic-ingest with perf8

### ISSUE THREAD

**Issue by prashant-elastic** [elastic/connectors-python#250]
## Bug Description
Error on executing elastic-ingest with perf8

### To Reproduce
1. Make necessary changes in config.yml file and connector.py file
2. Execute the command: <path>/bin/perf8 --memray --pyspy --psutil -c <path>/bin/elastic-ingest --one-sync --sync-now --debug

## Actual behavior
1. Error is thrown and command execution stops
`Traceback (most recent call last):
  File "/home/ubuntu/perf8test/es-connectors/bin/perf8", line 33, in <module>
    sys.exit(load_entry_point('perf8==0.0.0', 'console_scripts', 'perf8')())
  File "/home/ubuntu/perf8test/es-connectors/lib/python3.10/site-packages/perf8/cli.py", line 123, in main
    if args.memray and args.gprof2dot:
AttributeError: 'Namespace' object has no attribute 'gprof2dot'

## Expected behavior
1. Command execution should be successful
3. Ingestion should happen successfully and perf8 report should be generated

## Screenshots
![perf8-error](https://user-images.githubusercontent.com/103035276/208590367-542b7d37-d445-4de5-9dad-d7bd9d2dfcf3.JPG)
`

## Environment
Amazon EC2 t3.small

- OS:
1. Ubuntu v22.04

## Additional context
This issue has been observed for Google Cloud Storage connector and Amazon S3 connector

**Comment by tarekziade** [comment]
please reinstall the latest main version of perf8 (you might need to delete the one installed) -- it should fix it

**Comment by tarekziade** [comment]
you can also use `--refresh-rate 15` to reduce the perf data file

**Comment by prashant-elastic** [comment]
Using --refresh-rate 15, approx 31GB of disk space was utilized for around 15k docs indexed and for --refresh-rate 60, approx 31 GB of disk space was utilized for around 16k docs indexed.
The available disk space on the system is 31 GB so full disk space was utilized

![ds-perf8-report-folder](https://user-images.githubusercontent.com/103035276/208675901-453cd24f-cdc8-474e-95da-93b11b2de24a.JPG)

This was carried out on an Amazon EC2 instance. In the meantime, we are also trying out on local VM
Let us know your thoughts on this.

**Comment by tarekziade** [comment]
The `--refresh-rate` only reduces the psutil csv file. Not the memray one.

You can deactivate it and we can just have memray for smaller benches

For MySQL I introduced 3 sizes: small/medium/large https://github.com/elastic/connectors-python/blob/main/connectors/sources/tests/fixtures/mysql/loadsample.py#L12-L15

maybe you can do the same here, and for the big one we'll deactivate memray. We don't need it if we have it with smaller tests, memory leaks will be visible even with 1k docs

**Comment by prashant-elastic** [comment]
This observation is not with ftest. This is when we execute elastic-ingest command.

**Comment by tarekziade** [comment]
I don't understand this last comment. Run it like this:

```
/bin/perf8 --pyspy --psutil --refresh-rate 15 -c /bin/elastic-ingest --one-sync --sync-now --debug
```

**Comment by prashant-elastic** [comment]
We executed elastic-ingest command without memray, and approx 51,591 documents got indexed successfully and high disk space utilization was not observed. But, we faced an error at the end of execution- Attaching Screenshot of the error for reference:

![error-perf8-exec](https://user-images.githubusercontent.com/103035276/208943258-db9c5390-bef4-4a5e-bdd0-65315c4207f7.JPG)

**Comment by tarekziade** [comment]
Thanks, I could reproduce it. Fixed by https://github.com/elastic/perf8/commit/5a565422eddcdc17a42ce287eac2c8713cc7b123

could you try again?

**Comment by prashant-elastic** [comment]
We tried this and it works fine. It is no more reproducible. Thanks !

**Comment by tarekziade** [comment]
awesome!
