### ISSUE TITLE
Document Network Drive and S3

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#260]
### Problem Description
Native connectors are documented on https://www.elastic.co/guide/en/enterprise-search/current/native-connectors.html but there is no customer facing documentation for connector clients, as the expectation is that customers refer to the repo as the main source of documentation in this scenario (as with the previous connector packages)

### Proposed Solution
We need to document Network drive and S3 for 8.6 and provide guidance for the customers that use self-managed connectors.
Doc should be added under https://github.com/elastic/connectors-python/tree/main/docs.

PM suggestion: to add each connector client in [DEVELOPING.md](https://github.com/elastic/connectors-python/blob/main/docs/DEVELOPING.md) as a header with connector specific info, and keep generic features grouped as for  [Sync](https://github.com/elastic/connectors-python/blob/main/docs/DEVELOPING.md#how-a-sync-works).
@tarekziade does this align with your vision?

Expected content (or links to content for ease of use):
- Direct link to the connector client
- Availability and prerequisites (Tech preview disclaimer)
- Setup and basic usage
   - running covered in [CONFIG.md](https://github.com/elastic/connectors-python/blob/main/docs/CONFIG.md#run-the-connector-service-on-prem) 
- Configuration settings (with defaults)
- Data extraction
- Known limitations
- Supported compatible versions

**Comment by danajuratoni** [comment]
cc: @leemthompo @chriscressman

**Comment by praveen-elastic** [comment]
Hi @danajuratoni, just to confirm, do we need to create a separate readme for each connector client and add a link to that in  [DEVELOPING.md](https://github.com/elastic/connectors-python/blob/main/docs/DEVELOPING.md) or shall we add the content for both s3 and network drive in [DEVELOPING.md](https://github.com/elastic/connectors-python/blob/main/docs/DEVELOPING.md) directly ?

**Comment by danajuratoni** [comment]
My suggestion is to add the content directly in [DEVELOPING.md](https://github.com/elastic/connectors-python/blob/main/docs/DEVELOPING.md).
We'd need a section for each connector client, so it can be referenced independently. Same for generic features such as e.g. extraction.

**Comment by tarekziade** [comment]
I've suggested having one file per connector in the docs to avoid keeping all the doc in a single file, we can always list them in a TOC in `DEVELOPING.md`

**Comment by ppf2** [comment]
>Supported compatible versions

Let's also state whether the Amazon S3 connector supports S3-compatible vendors or if it's limited to Amazon S3 only.

**Comment by danajuratoni** [comment]
>I've suggested having one file per connector in the docs to avoid keeping all the docs in a single file

I'm waiting for our docs team for the final documentation strategy, so this ticket applies only to the 2 *connector clients* mentioned. Current agreement is to document connector clients in the repo as soon as they are finished (thus decoupling the dev process from the release) and _move it_ to Elastic docs as soon as possible.

**Comment by danajuratoni** [comment]
@leemthompo @chriscressman could one of you please take a quick look at the documentation in the linked PR? Thanks!

**Comment by parth-crest** [comment]
> > Supported compatible versions
> 
> Let's also state whether the Amazon S3 connector supports S3-compatible vendors or if it's limited to Amazon S3 only.

@ppf2 As of now It's limited to s3 only. we would not be able to fetch data from s3 compatible vendors.

**Comment by chriscressman** [comment]
> @leemthompo @chriscressman could one of you please take a quick look at the documentation in the linked PR? Thanks!

:+1: I added my review

**Comment by leemthompo** [comment]
Taking a look now!
