### ISSUE TITLE
Original exception body is missing

### ISSUE THREAD

**Issue by jignesh-crest** [elastic/connectors-python#284]
### Problem Description

When [byoc initializes](https://github.com/elastic/connectors-python/blob/4ca7026e8c3c67950703b18eaf3bd61074b3d14a/connectors/byoc.py#L448) the source class, on encountering an exception it raises a [generic exception
](https://github.com/elastic/connectors-python/blob/4ca7026e8c3c67950703b18eaf3bd61074b3d14a/connectors/byoc.py#L463)
It doesn't contain any information from the originally raised exception.

### Proposed Solution

the logger message from [this](https://github.com/elastic/connectors-python/blob/4ca7026e8c3c67950703b18eaf3bd61074b3d14a/connectors/byoc.py#L463) line can be changed to this to let user know the actual exception:
raise DataSourceError(f"Could not instantiate {fqn} for {service_type}. Exception encountered : {e}")

**Comment by artem-shelkovnikov** [comment]
As mentioned in the PR, does this change make sense?

Kibana UI is supposed to display human-friendly actionable errors. This error is not operator-actionable as it requires changes to the connector code.

Connector in normal conditions should never display this error at all - it means that there's a bug either in framework or connector code that prevents class from initializing and customer can actually do nothing about it.

**Comment by jignesh-crest** [comment]
> This error is not operator-actionable as it requires changes to the connector code.

This change is done to let the user know that there are some configurations that were not entered properly when configuring the source from Kibana UI. If we do not pass the actual exception, In that case, the user will just get the custom exception saying "Could not instantiate class ....." but the user might not get an idea of what was wrong and what needs to be updated.

That's why we have just added the actual exception message, If you want we can close this PR and the Issue attached.

Do let us know your thoughts on the same. 

cc @tarekziade @nirav-elastic

**Comment by artem-shelkovnikov** [comment]
I don't think that invalid connector configuration should lead to terminal failure when instantiating a connector class. If we want this to happen still - invalid connector configuration raising exceptions - I would then provide a different exception class for it that is thrown by connector if configuration is invalid - and catch and handle it properly on the framework level. We still need to separate invalid configuration VS problems instantiating a connector class due to code/framework issues.

**Comment by jignesh-crest** [comment]
Hey, What we can do is, similar to the [tweek_bulk_options](https://github.com/elastic/connectors-python/blob/542ea295750689baefc39289ca14fd996363b68a/connectors/source.py#L217) method we can create the validate_configuration_parameters method in the Base source class. This will be useful to both framework and individual connector source classes. as,
- It can validate all the configuration parameters if needed by the source class by overriding the method from the parent base class.
- The exception raised can directly be delivered to the Kibana UI, This way we will have control over the error message.
- This method will be called [before ](https://github.com/elastic/connectors-python/blob/542ea295750689baefc39289ca14fd996363b68a/connectors/byoc.py#L584)pinging the source, just like tweek_bulk_options.

Let us know if you want us to do the change.

**Comment by tarekziade** [comment]
@jignesh-crest I think that's an excellent idea! It will also improve the standardization of our error handling 

I would advise to:
- create a specific error class we can bubble up to the FE
- use a shorter name like `validate_config`

@timgrein if you have some ideas on how this can align well with what we're doing with the filtering rules validation

**Comment by jignesh-crest** [comment]
> @jignesh-crest I think that's an excellent idea! It will also improve the standardization of our error handling
> 
> I would advise to:
> 
> * create a specific error class we can bubble up to the FE
> * use a shorter name like `validate_config`
> 
> @timgrein if you have some ideas on how this can align well with what we're doing with the filtering rules validation

Hey @timgrein, do you have any suggestions on this since the filtering PR got merged in the main?

**Comment by jignesh-crest** [comment]
Closing this issue now as #552 would be used for delivering the validation exceptions to Kibana UI.
