### ISSUE TITLE
Pin the requirements

### ISSUE THREAD

**Issue by praveen-elastic** [elastic/connectors-python#307]
### Problem Description

The libraries used by respective connectors should be pinned in order to avoid unexpected behaviour due to breaking changes at the package level.

### Proposed Solution

```
aiogoogle==4.2.0
azure-storage-blob==12.13.0
aiomysql==0.0.22
aioboto3==9.0.0
smbprotocol==1.9.0
```

**Comment by tarekziade** [comment]
Yeah thanks, not sure why they were not pinned in the first place here
