### ISSUE TITLE
emit a single line on errors when `--filebeat` is used

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#324]
### Problem Description

When `--filebeat` is used and an error is raised, we should emit a single line 

https://github.com/elastic/enterprise-search-team/issues/3706

**Comment by DianaJourdan** [comment]
Is it a duplicate of https://github.com/elastic/enterprise-search-team/issues/3706?

**Comment by seanstory** [comment]
Yes, this is a duplicate. Closing
