### ISSUE TITLE
Add the ability to have a list of connection_id's per custom connector source_type

### ISSUE THREAD

**Issue by elastickent** [elastic/connectors-python#349]
### Problem Description
I am unable to have multiple instances of a custom connector

### Proposed Solution
Allow multiple connect_id's per custom source.

**Comment by seanstory** [comment]
Hi @elastickent - Please use https://github.com/elastic/enhancements for filing internal enhancement requests. That's where product management is looking most closely.

As a side note, please edit your Github profile to include your full name. That way I can find you on slack next time. :)
