### ISSUE TITLE
Default S3 bucket list syntax causes a sync failure

### ISSUE THREAD

**Issue by ppf2** [elastic/connectors-python#362]
We set a default value for list of buckets in the s3 connector that gets displayed on the UI configuration form: https://github.com/elastic/connectors-python/blob/542ea295750689baefc39289ca14fd996363b68a/connectors/sources/s3.py#L216

However, if you run a sync (8.6.0) using the default value as a template syntax, it will throw an error:

<img width="603" alt="image" src="https://user-images.githubusercontent.com/7216393/213588228-918b61cc-a31d-4c13-9d23-e96fbca66a06.png">

**Comment by akanshi-crest** [comment]
@ppf2 This sync failure is happening because of the framework change so please update the label to enhancement

**Comment by akanshi-crest** [comment]
Do we have to raise exception in case of passing empty strings `""` in buckets configuration or we have to index data for all the buckets?

**Comment by ppf2** [comment]
I like the idea of supporting `*` but not allowing blank to automatically fetch all buckets.  If we support this, it will be helpful to have some helper/tooltip text directly on the UI in addition to documenting the syntax.

**Comment by tarekziade** [comment]
yeah agreed, an explicit `*` sound good. As far as multiple buckets go, we don't support lists in Kibana yet, and what we did for the other connectors is to use a string with `,`'

so:

- `*`
- `bucket`
- `bucket1,bucket2`


Commas separated items will be automatically converted to a list in the framework, if we use the type `list` for the field, see https://github.com/elastic/connectors-python/blob/main/connectors/source.py#L53

**Comment by parth-crest** [comment]
Hey @tarekziade, A minor nit: With this line, [[item.strip() for item in value.split(",")]](https://github.com/elastic/connectors-python/blob/main/connectors/source.py#L53) when user passes empty string we need to check for `[""]` in the if condition.
As a nit can we update the line to `[item.strip() for item in value.split(",")] if value != "" else []` like this so we can just check for the `if len(list) > 0` since we are passing type: "list" in the `get_default_configuration()`.

**Comment by danajuratoni** [comment]
An empty field should never fetch all objects, this is something we all agree on.

However I see at least 2 ways of retrieving all fields in UI
1. a checkbox/toggle to include everything (that would deactivate the input test field if used) e.g.
![image](https://user-images.githubusercontent.com/102797748/216104583-2b85501d-76e3-4c03-a895-0341621c29d9.png)

2. the consistent use of `*` in the field, as an operator to include everything

<img width="466" alt="image" src="https://user-images.githubusercontent.com/102797748/216105083-832c6984-e50a-4f77-8676-530d1036f086.png">

@zombieFox is there a design guideline for this type of thing?
