### ISSUE TITLE
Display the most useful columns by default in Documents UI for S3 connectors

### ISSUE THREAD

**Issue by ppf2** [elastic/connectors-python#363]
Here's a documents view of synced documents from S3:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/7216393/213588913-0846d42a-22bb-4fb1-9e66-8888f28583c4.png">

You will see that by default, it displays 3 dummy columns, but it is inconsistent.  Some records show the filename in the default 3 column view, but other records do not.  

A better experience will be to always display the 3 most useful fields.  I think the issue here is that we always display the first 3 returned:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/7216393/213589110-0425051c-b26d-47ef-8151-65ddc83c71aa.png">

So if the document had an extraction done against it, the filename is missed in the default view because it is now the 4th entry.  Instead of always displaying only the first 3 fields, it will be helpful to actually define 3 specific fields to display, e.g.

- bucket
- filename
- body

An even better approach will be to let the user configure their desired default fields to display.

**Comment by ppf2** [comment]
Also when displaying `size`, it will be helpful to include the unit of measure.

**Comment by ppf2** [comment]
We may also want to add a tooltip to `_timestamp` column in the Documents view to indicate that this is the timestamp of when the document is indexed to Elasticsearch (not to be confused with the timestamp of the document within S3).

**Comment by akanshi-crest** [comment]
> Also when displaying `size`, it will be helpful to include the unit of measure.

sure we'll add this with size.

**Comment by akanshi-crest** [comment]
> We may also want to add a tooltip to _timestamp column in the Documents view to indicate that this is the timestamp of when the document is indexed to Elasticsearch (not to be confused with the timestamp of the document within S3).

> Display the most useful columns by default in Documents UI for S3 connectors

> An even better approach will be to let the user configure their desired default fields to display.

These 3 points needs to taken care at the framework level or the UI level. We will update the PR with adding the measurement unit for size. 

cc: @tarekziade

**Comment by khusbu-crest** [comment]
Can we close this enhancement as the PR for the same is merged? 
CC: @tarekziade  @ppf2

**Comment by danajuratoni** [comment]
Measurement unit for size was added. Making improvements to the documents view is something impacting all ingestion methods, so I'll be moving this part to be together with other usability enhancements requests. cc: @serenachou
