### ISSUE TITLE
Azure Blob Storage connector client (8.7 Beta)

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#402]
## New Azure Blob Storage connector
New connector client to be released with 8.7 in Beta.
**8.7 Feature Freeze** on 7th Feb 2023
**8.7 GA** on Tue, Mar 28 2023

### Acceptance criteria
- [x] TDD in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf) 
- [x] QA plan in [GDrive](https://drive.google.com/drive/folders/1DN2y4TRXIuybX8vawHljkWozoyPEOYaf)
- [x] Code merged in main following the defined PR process
- [x] Functional tests performed
- [x] Performance test/ reports against the last stable release branch of the connector framework and in Elastic Cloud 
     - intial performance tests https://docs.google.com/document/d/1joQC2azhnPq-4O9wDH3GMtz1_OFuzdER/edit 
- [x] Connector client documentation in repo 
- [x] Demo of the connector in latest builds in Elastic Cloud
     - https://drive.google.com/drive/folders/17lKKqV8y_o-RoIPSEIKg2AoZlXIUlk0m
- [x] Sign off given from an engineer in Ingestion
     - [x] Code backported to the correct version 
     - [x] Automated tests to 90% coverage
- [x] Regression test suite performed for the release along with QA day for all supported OS in https://www.elastic.co/support/matrix 
- [x] https://github.com/elastic/connectors-python/issues/471

~- [ ] Test - ‘native’ version~ not applicable for 8.7

**Comment by danajuratoni** [comment]
Linking main PRs
https://github.com/elastic/connectors-python/pull/274
https://github.com/elastic/connectors-python/pull/401

**Comment by parth-crest** [comment]
Acceptance criteria #5 for performance testing has been done and it has been tested on 8.7 branch. Stats are available in GDrive. Please take a look. Once reviewed from your end, we can close this issue.

**Comment by danajuratoni** [comment]
Closing issue as done.
