### ISSUE TITLE
The E2E test is not getting completed without manual intervention (press Ctrl+C)

### ISSUE THREAD

**Issue by khusbu-crest** [elastic/connectors-python#424]
## Bug Description
The E2E test is not getting completed without manual intervention

### To Reproduce
1. Check out the latest code and Go to the directory.
2. Execute the E2E test command as make ftest NAME=postgresql
3. Wait till the execution of the E2E test shows the logs as attached 

## Expected behavior
We expect the E2E test execution should get completed on its own, without any manual intervention (press Ctrl+c)

## Screenshots
PFA
![e2e test not getting completed](https://user-images.githubusercontent.com/96513296/217222493-f156b81e-139d-4344-acba-c37d43fe95b8.png)

## Environment
CentOS

## Additional context
Please confirm if this is the expected behavior that the executor has to manually end the E2E test script by pressing Ctrl+c or if it should end on its own.

**Comment by khusbu-crest** [comment]
seems resolved with the latest pull.

**Comment by tarekziade** [comment]
Yeah we had that issue and it got resolved with https://github.com/elastic/connectors-python/pull/285
