### ISSUE TITLE
move to python 3.11

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#452]
After the 8.7 branch is done, let's move to `3.11` to benefit from the latest improvements

**Comment by DianaJourdan** [comment]
What is the time frame for this change? Can we push it after 8.8 FF?

**Comment by seanstory** [comment]
I don't think this is something we need to spend time on. At some point, we can put effort into working on multiple versions, but chasing the bleeding edge does not bring us substantial value for the effort.
