### ISSUE TITLE
Getting `mapper_parsing_exception` while indexing JIRA documents into Elastic Search

### ISSUE THREAD

**Issue by moxarth-elastic** [elastic/connectors-python#461]
## Bug Description
While working with the Jira connector, our Jira server has approx. 4641 documents including projects, issues and attachments. I tried to index them into the Elastic Search and facing `mapper_parsing_exception` for exceeding the fields limit of 1000 and successive documents gets missed.

## Screenshots
![image](https://user-images.githubusercontent.com/96762084/218419291-fb5d545b-c937-422e-9a42-9e062cf40844.png)

**Comment by tarekziade** [comment]
> Jira server has approx. 4641 documents including projects, issues and attachments

`mapper_parsing_exception` can be raised by config, but maybe each type of document should be indexed into a distinct index.

**Comment by danajuratoni** [comment]
More than 1000 fields! How many types are there and how many fields/type? Not sure that splitting the problem would solve this issue long term.

**Comment by moxarth-elastic** [comment]
User can create custom fields as many as he wants. So, we can not measure the number of fields present in the jira response.

**Comment by moxarth-elastic** [comment]
As per the discussion with @tarekziade in technical meeting, user needs to update the [configurations](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-settings-limit.html) from the deployment settings itself and there won't be any change at the connector or framework level. Hence, closing this issue since it is no longer needed.
cc: @danajuratoni @nirav-elastic
