### ISSUE TITLE
Adding support to run e2e tests for Postgresql & Oracle in the Mac book with M1 chip.	

### ISSUE THREAD

**Issue by khusbu-crest** [elastic/connectors-python#512]
### Problem Description
Adding support to run e2e tests for Postgresql & Oracle in the Mac book with M1 chip.	

The e2e tests for Postgresql & Oracle not running successfully in the Mac book with M1 chip.	

While running e2e for Postgresql - it is showing an error for asyncio. There is a known issue of sqlalchemy of missing greenlet lib on M1 and it needs to be expliclity installed: https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#asyncio-install 

And while running e2e for Oracle, a connection refused error is shown.

### Proposed Solution
For postgresql, we will be adding `pip install sqlalchemy[asyncio]` into the dependencies. 

And for oracle, we are finding out the solution.

### Additional Context: 
Once this is done, we are planning to check the support of M1 chip for the existing connectors.

**Comment by moxarth-elastic** [comment]
> Hey @tarekziade , For Oracle e2e, we found a few issues with running Oracle on M1chip. Also, there are no official images available for the M1 machines. Here is a [link](https://github.com/oracle/docker-images/issues/2184#issuecomment-1046884609) to one of the solutions we are working on. So the concern here is, either we must add Colima(mentioned in the link) as a dependency for Oracle e2e or skip running Oracle E2E on M1. Let us know your thoughts on the same.
> 
> cc: @danajuratoni

Hey, @tarekziade do you have any suggestion for this issue ?

**Comment by pedroaugustofsilva** [comment]
> @tarekziade We have verified Oracle on Linux Arm. It is working fine.

Where do you get the Oracle image? I'm with the same problem here.

**Comment by praveen-elastic** [comment]
Hi @pedroaugustofsilva, we were only able to verify the working of Oracle lib and the Oracle connector on ARM. Oracle image didn't work.
