### ISSUE TITLE
Use ABCs in all base classes

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#573]
We’re introducing ABCs in the project [here](https://github.com/elastic/connectors-python/blob/main/connectors/sources/generic_database.py#L53)  -- we might as well do the same for every base class that requires to be overriden

Candidates:

- `BaseService` https://github.com/elastic/connectors-python/blob/main/connectors/services/base.py#L17
- `BaseDataSource` https://github.com/elastic/connectors-python/blob/main/connectors/source.py#L111

What's the benefit you may ask?
we can check if a concrete class has implemented the methods we've asked for

```
import inspect

if inspect.isabstract(SourceInstance):
    raise TypeError("Dude, your implementation is incomplete, we can't use this"
```

**Comment by seanstory** [comment]
closing, as raising "not implemented errors" have accomplished the same.
