### ISSUE TITLE
Deleted document count displayed in the console along with the created document count

### ISSUE THREAD

**Issue by prashant-elastic** [elastic/connectors-python#59]
## Bug Description
After creating a new index and indexing new set of documents, in the console it shows deleted document count along with the created count

## Pre-requisites
1. An index already exists with 50k docs indexed
2. Create a new index from the UI
3. Generate the API key and assign privileges to the API key
4. Configure config.yml file with proper API key and source.py file(with a database name having limited records - 28 for this case) with appropriate parameter values
5. Update the package

### To Reproduce
1. Execute the indexing using the command elastic-ingest -c config-file --action poll
2. Set schedule in the UI for every 1 minute and click Sync
3. Observe the execution process and the logs printed

## Expected behavior
Count should be displayed as {'create': 28} and Sync done: 28 indexed, 0 deleted

## Actual behavior
Count is displayed as {'create': 28, 'delete':50000} and Sync done: 28 indexed, 50000 deleted. This deleted document count refers to the count of the document indexed in the older index which is 50k

## Screenshots
<img width="1440" alt="indexed and deleted document count" src="https://user-images.githubusercontent.com/103035276/191237989-ef54daf2-f68b-4b73-ac0d-a399ad04737f.png">

## Environment
Elasticsearch v8.4.1
macOS Monterey v12.5

**Comment by artem-shelkovnikov** [comment]
Closing as it's stale and already irrelevant
