### ISSUE TITLE
Network Drives - support SMB 3.0 

### ISSUE THREAD

**Issue by serenachou** [elastic/connectors-python#598]
From our field team: 

Are we planning on supporting SMB 3.0 in the future as the current pysmb package used within the network drives connector doesn't support > SMB 2.01

Add support for SMB 3.0 for the network drives connector client.

**Comment by praveen-elastic** [comment]
Hey @serenachou, The previous connector package on Workplace Search uses pysmb due to which it only supports SMB v1 and v2. 
However the present Network Drive connector client uses [smbprotocol](https://github.com/jborean93/smbprotocol) library of Python which supports both SMB v2 and v3.
