### ISSUE TITLE
Improve messaging for case when connector needs configuration

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors-python#602]
### Problem Description
When connector is just created and not configured, python framework reports that sync cannot happen with the following message:

```
[FMWK][12:19:01][INFO] Can't sync with status `needs_configuration`
```

This message is not user-friendly and lacks action points.

### Proposed Solution
Change message that's reported to be actionable, for example it can be one of:

- "Your connector <name> has connected to Enterprise Search successfully.  However, it requires further configuration before a sync can be initiated.”"
- "Connector <name> is not configured and will not sync. Please configure the connector using Kibana."

**Comment by tarekziade** [comment]
since it's a service CLI, not a front end, another option would be to display just error codes, along with a doc that provides details for each error code

**Comment by artem-shelkovnikov** [comment]
> since it's a service CLI, not a front end, another option would be to display just error codes, along with a doc that provides details for each error code

@tarekziade do you mean displaying something like "ERROR - invalid_connector_status" in terminal instead of human-readable message and having a doc somewhere explaining the statuses?

**Comment by artem-shelkovnikov** [comment]
I've provided an example PR with human-friendly messages. I think error codes are good, but then the change to introduce them should be much wider to touch as many actionable errors as possible.
