### ISSUE TITLE
Remove not useful defaults for configurable fields

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#606]
## Bug Description
Not useful defaults should not be provided for configurable fields. e.g. devstoreaccount1 as account name or an account_key in Azure Blob storage. We will keep defaults where it simplifies the user experience, for fields such as `fetch_size` or `retry_count`.

Useful examples for config parameters such as the example for blob_endpoint should be provided in the documentation and once we have rich configurable fields, as tooltips.

**Preliminary list with configurable fields that don't need defaults**
ABS: account_name, account_key, blob_endpoint
Google Cloud Storage: service_account_credentials
Generic DB: host, port, username, password, database
Oracle: -
Postgres: -
MSSQL: mssql_driver
Network drive: username, password, server_ip, server_port, drive_path
etc.

## AC
- [ ] Provide only useful default values all connector clients. See preliminary list above for examples.
- [ ] Update documentation to reflect changes.
- [ ] If Rich configurable fields available, add tooltip information.

**Comment by danajuratoni** [comment]
cc: @navarone-feekery

**Comment by artem-shelkovnikov** [comment]
I think it's not possible until the job to make our functional tests have custom connector configuration is done.

**Comment by navarone-feekery** [comment]
@danajuratoni I can look at this alongside https://github.com/elastic/enterprise-search-team/issues/4198

@artem-shelkovnikov could you point me to what functional tests need to be updated for this to work? And is someone already working on it?

**Comment by danajuratoni** [comment]
@navarone-feekery just making sure you're aware of this issue, but probably it's already on your radar

**Comment by navarone-feekery** [comment]
Because of time constraints I will look at this after working on Kibana, so closer to/just after FF.
I have a draft PR that is half-finished, but it's impacting ftests too much so is taking more time than I expected to complete: https://github.com/elastic/connectors-python/pull/761

**Comment by danajuratoni** [comment]
@navarone-feekery Will this make it to 8.8?

**Comment by navarone-feekery** [comment]
@danajuratoni because I am on SDH this week I don't think this will make it to 8.8.

If someone wants to take it over, I have a draft PR that addresses the core issue: https://github.com/elastic/connectors-python/pull/761, but only for a few connectors.
All that's required for the remaining connectors is:

- remove the `value` field from every configurable field entirely
- add an appropriate `connector.json` to the ftest directory for that connector
- ensure none of the connector ftests were broken by this change

**Comment by DianaJourdan** [comment]
@danajuratoni I discussed with Nav and this one will take more time to update the ftest and validate. I propose we keep it for a later sprint

**Comment by danajuratoni** [comment]
@DianaJourdan is this something that @efegurkan could take over as part of the 8.9 work?

**Comment by navarone-feekery** [comment]
@danajuratoni the project has evolved since this issue was created so I don't know if the acceptance criteria is still relevant.
I've applies changes now that effectively remove _all_ `value` fields from the default configuration. I made exceptions for booleans and dropdowns, as they need an initial value. Do you consider that enough to close this issue?

**Comment by artem-shelkovnikov** [comment]
Additional note:

There are still a little bit of space to improve configs. Some of our connectors provide tooltips on how to set up the field values (e.g. "For client id, go to Azure portal and find it there". Some can still have nice default fields like "port: 3306" for MySQL.

It would be nice to come up with a guideline for configurable fields - which default values make sense, should tooltip be required, etc.

**Comment by navarone-feekery** [comment]
I also think we should also re-think naming here. We have a field already called `default_value` which contains a value that will be used if the `value` field is empty. This is only relevant for fields that aren't `required` right now.
When we talk about initialising the configuration with a pre-determined `value`, I suggest we begin calling it a **"preset" value**. WDYT?

**Comment by artem-shelkovnikov** [comment]
TBH I find default_value/value confusing and non-transparent. I'd honestly like to drop it fully if possible, do you think it's reasonable?

I think same functionality can be achieved by more strict validation.

E.g.: Field: Default_Timeout, value: None, default_value: 30 can be instead value: 30, validation: >1, < 60 (is it actually possible now?)

**Comment by navarone-feekery** [comment]
That's entirely possible to remove. I think the only changes required would be to update the `Field` class ([specifically here](https://github.com/elastic/connectors-python/blob/ca1cea81525ee50ea90b853c92bc29ddfb4a5b91/connectors/source.py#L99-L111) where we get `default_value` if applicable).

I think `default_value` was added to fulfill a specific UI use-case, where we want to have values that are `required: False`. If we remove `default_value` all fields will need to be required.

**Comment by navarone-feekery** [comment]
The main task for this issue is complete, if anyone has any further discussion we can have it in a new issue or on slack.
