### ISSUE TITLE
Try out `pytds` for MSSQL

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#623]
Let's try to move to SQLAlchemy + PyTSD and see if it works

package: `sqlalchemy-pytds`

it's a blocking lib, so we'll need to tweak accordingly

**Comment by tarekziade** [comment]
https://github.com/elastic/connectors-python/pull/624

**Comment by tarekziade** [comment]
Good news, it seems to works well https://buildkite.com/elastic/connectors-python-nightly/builds/435#0187112e-0b99-4419-b35a-29872f0bda71

**Comment by moxarth-elastic** [comment]
For documentation changes we need to remove `mssql_driver` and `secured_connection` parameter with OpenSSL note from the configuration. Also, We need to remove prerequisite of ODBC Driver from the documentation as we do not require any driver to run MS-SQL connector.

We need to add few parameters as following:

##### `schema`

Name of the Microsoft SQL Server schema. Default value is `dbo`. Examples:

  - `dbo`
  - `custom_schema`

##### `ssl_enabled`

SSL verification should be enabled or not. Default value is `False`.

##### `ssl_ca`

Content of SSL certificate. If SSL is disabled, keep the `ssl_ca` field empty. Example certificate:

  - ```
    -----BEGIN CERTIFICATE-----
    MIID+jCCAuKgAwIBAgIGAJJMzlxLMA0GCSqGSIb3DQEBCwUAMHoxCzAJBgNVBAYT
    ...
    7RhLQyWn2u00L7/9Omw=
    -----END CERTIFICATE-----
    ```

##### `validate_host`

Validate host should be enabled or not. Default value is `False`.

**Comment by danajuratoni** [comment]
@moxarth-elastic @tarekziade does this change have a performance impact?

**Comment by artem-shelkovnikov** [comment]
@danajuratoni you can check Perf8 reports in https://github.com/elastic/connectors-python/pull/678, TLDR - barely any performance impact.

**Comment by leemthompo** [comment]
> We need to remove prerequisite of ODBC Driver from the documentation as we do not require any driver to run MS-SQL connector.

@moxarth-elastic Do users still require the `sysadmin` server role?

**Comment by moxarth-elastic** [comment]
> > We need to remove prerequisite of ODBC Driver from the documentation as we do not require any driver to run MS-SQL connector.
> 
> @moxarth-elastic Do users still require the `sysadmin` server role?

Yes, we need `sysadmin` server role to run the connector. We just need to remove the prerequisite of ODBC driver.

**Comment by leemthompo** [comment]
Docs tasks are done for this one.

**Comment by khusbu-crest** [comment]
Closing this issue as PR is merged and the documents are updated.
