### ISSUE TITLE
Conversion to `base64` adds a EOL for macOS

### ISSUE THREAD

**Issue by moxarth-elastic** [elastic/connectors-python#626]
### Problem Description
While converting to `base64` via code, platform such as macOS adds a EOL in the generated file. So, we need to remove it to make it similar in behavior to other platforms.

**Comment by artem-shelkovnikov** [comment]
I remember a PR about it in past, did it start happening again after recent changes?

cc @tarekziade

**Comment by artem-shelkovnikov** [comment]
@moxarth-elastic can you confirm if the issue still happens?

**Comment by moxarth-elastic** [comment]
> @moxarth-elastic can you confirm if the issue still happens?

Sure, let me check it

**Comment by moxarth-elastic** [comment]
@artem-shelkovnikov seems like the issue is fixed, i don't see an EOL after converting a file with base64.

**Comment by artem-shelkovnikov** [comment]
Sounds good, closing the issue then!
