### ISSUE TITLE
The configuration parameters are not getting saved and showing error as - [request body.password.depends_on]: definition for this key is missing

### ISSUE THREAD

**Issue by khusbu-crest** [elastic/connectors-python#638]
## Bug Description
The configuration parameters are not getting saved and showing an error as - `[request body.password.depends_on]: definition for this key is missing`

### To Reproduce
1. Add host, api_key, connector ID, and service type in the config.yml file
2. Execute command make run
3. Update the configurations and click the SAVE button to change the configurations on the UI

## Expected behavior
The configuration parameters should get saved without any errors and the sync should consider the updated parameter values

## Screenshots
![configuration parameters are not getting saved](https://user-images.githubusercontent.com/96513296/227902188-1b4fbefe-b001-4190-864e-ab742cc827bf.png)

## Environment
- Cent OS7
- Chrome Browser
- Version 110.0.5481.178

## Additional context
It seems the error is appearing because the parameter values are expected to be of string/declared datatype.

**Comment by navarone-feekery** [comment]
@artem-shelkovnikov sorry I missed this notification
This is actually a different problem from the one we discussed. I'll investigate it now.

**Comment by navarone-feekery** [comment]
I can't replicate this issue exactly.

@khusbu-crest I notice that the connector is named "search-confluence3" -- is this for a connector that's still in development? If so do you have a branch I can pull to test this on?

**Comment by khusbu-crest** [comment]
@navarone-feekery  It is the issue with Index getting created on Elastic Search - v-8.6.2. The configuration parameters are not getting saved, after executing make run command. An error, while saving the parameters (attached in the issue), getting displayed.
Hereby, attaching the screen recording for the issue as well, for your reference.

Video uploaded to Elastic google drive: - https://drive.google.com/file/d/1FIof0BPAIG4tBdJ2_-bE7kd4iWgw-Lx_/view?usp=share_link

**Comment by navarone-feekery** [comment]
@khusbu-crest thank you for the screen recording. I have some followup questions:

1. What version of connectors-python are you developing on?
2. Are you able to pull the latest 8.8 Kibana snapshot and see if it's still occurring?

**Comment by khusbu-crest** [comment]
@navarone-feekery  Please find the response below:

1. What version of connectors-python are you developing on? --> **main branch**
2. Are you able to pull the latest 8.8 Kibana snapshot and see if it's still occurring? --> **Yes, the Issue is still occurring**. We have checked it for **Generic Database Connector - Oracle** as the **Confluence connector** is yet to be merged in the **main** branch - PFA. 
![8 8 snapshots shows error for configuration parameters - gdc1](https://user-images.githubusercontent.com/96513296/228556598-631d323e-ad0b-4a98-9f6a-760ce6c9b27f.png)

**Comment by navarone-feekery** [comment]
@khusbu-crest thanks for confirming. I was able to replicate your issue on an older Kibana commit, but if update Kibana to the very latest 8.8.0 snapshot (main branch) then this bug stops occurring.
How do you normally run Kibana? Can you confirm that you have the very latest pull from Kibana main branch running?

**Comment by navarone-feekery** [comment]
The latest snapshot includes commits up to here: https://github.com/elastic/kibana/commits/c770e9d6cb5c363f6eb865eb44bace59368fcc10
The commit that fixes your issue is included in it, so I just want to confirm that this bug is _still_ occurring or if the latest Kibana fixes it.

**Comment by navarone-feekery** [comment]
If you're using Kibana on cloud, it's possible that there's a delay between a patch being added to the latest snapshot and it being made available for use.
If you can run Kibana locally by cloning main, then this bug should be resolvable.

Alternatively, a temporary workaround:
If you go to the fields that are not of "expected value" and re-enter them, they will be input as strings and you should be able to save the configuration.

**Comment by navarone-feekery** [comment]
@khusbu-crest I'm glad we could resolve it on the latest Kibana version!
We will investigate how we can ensure backwards compatibility before 8.8 release, so let's leave this issue open until we either fix it or confirm that we won't support it.

**Comment by navarone-feekery** [comment]
This is no longer an issue.
