### ISSUE TITLE
Comment out advanced settings from config.yml

### ISSUE THREAD

**Issue by ppf2** [elastic/connectors-python#771]
Have we considered removing or commenting out the advanced settings from the default config.yml configuration file?  

Some users may have a tendency to tune a lot of these settings _just because they are there and enabled by default_ in the config.yml.  This may result in suboptimal performance configurations.

There are probably a few approaches we could take. Examples:

- Comment out the advanced settings and provide a description in the comment to indicate that it is an advanced setting
- Remove the advanced settings from the config.yml and refer them to the documentation for additional settings that are available
- Remove the advanced settings from the config.yml file, and provide a separate config.yml.all(or some other name) file that lists all the available settings).

**Comment by leemthompo** [comment]
Adding `ingestion` label because there's both an eng and docs component to Pius' proposal(s)

**Comment by danajuratoni** [comment]
Leaning towards option 1 proposed

> Comment out the advanced settings and provide a description in the comment to indicate that it is an advanced setting

This should be feasible for 8.8.

**Comment by artem-shelkovnikov** [comment]
@seanstory is this addressed by your work for configuration file in this release?

**Comment by seanstory** [comment]
Thanks for the tag!

Yep this is done. See https://github.com/elastic/connectors-python/blob/main/config.yml

I'm going to close this, but feel free to re-open if you feel that the current approach isn't what you were looking for.
