### ISSUE TITLE
Include search index name whenever we log an entry that includes the connector ID

### ISSUE THREAD

**Issue by ppf2** [elastic/connectors-python#775]
It will be helpful to include the search index name alongside the connector ID in our connector service logging so that users can easily tell which connector it is referring to without having to look up the ID from the `.elastic-connectors` index.  Thx!

```
[FMWK][21:50:58][DEBUG] Connector status is Status.CONNECTED
[FMWK][21:50:58][DEBUG] Filtering of connector UAhYeIcB4DIAFu1tTlw1 is in state valid, skipping...
[FMWK][21:50:58][DEBUG] scheduler is disabled
[FMWK][21:50:58][DEBUG] Scheduling is disabled for connector UAhYeIcB4DIAFu1tTlw1
[FMWK][21:50:59][DEBUG] Syncing 'mysql' for connector 'UAhYeIcB4DIAFu1tTlw1'
```

**Comment by DianaJourdan** [comment]
@chenhui with your [PR](https://github.com/elastic/connectors-python/pull/806), you have added the connector index name. We should be able to close also this ticket. @ppf2 just to make sure, this is what you asked for?

**Comment by ppf2** [comment]
Thanks @DianaJourdan @wangch079 Does this change also improve the lines (associated with a specific connector job) with no connector ID reference to begin with.  Will we start enriching these lines with connector IDs+index name as well?

```
[FMWK][10:51:54][INFO] Filtering validation started
[FMWK][10:51:54][INFO] Filtering validation result: FilteringValidationState.VALID
[FMWK][10:51:54][INFO] Filtering validation errors: None
[FMWK][10:51:54][INFO] Starting doc lookups
[FMWK][10:51:55][INFO] Fetcher <create: 0 |update: 0 |delete: 0>
[FMWK][10:51:57][INFO] Fetcher <create: 0 |update: 0 |delete: 0>
[FMWK][10:51:57][INFO] Fetcher <create: 0 |update: 0 |delete: 0>
[FMWK][10:51:57][INFO] Fetcher <create: 0 |update: 0 |delete: 0>
[FMWK][10:51:57][INFO] Fetcher <create: 0 |update: 0 |delete: 0>
```

**Comment by wangch079** [comment]
> ```
> [FMWK][10:51:54][INFO] Filtering validation started
> [FMWK][10:51:54][INFO] Filtering validation result: FilteringValidationState.VALID
> [FMWK][10:51:54][INFO] Filtering validation errors: None
> [FMWK][10:51:54][INFO] Starting doc lookups
> [FMWK][10:51:55][INFO] Fetcher <create: 0 |update: 0 |delete: 0>
> [FMWK][10:51:57][INFO] Fetcher <create: 0 |update: 0 |delete: 0>
> [FMWK][10:51:57][INFO] Fetcher <create: 0 |update: 0 |delete: 0>
> [FMWK][10:51:57][INFO] Fetcher <create: 0 |update: 0 |delete: 0>
> [FMWK][10:51:57][INFO] Fetcher <create: 0 |update: 0 |delete: 0>
> ```

Hi @ppf2 , did you get those logs with the latest `main` of `connectors-python`? I suspect no, as I see `Fetcher` in the log, which was renamed to `Extractor` months ago.

>Does this change also improve the lines (associated with a specific connector job) with no connector ID reference to begin with. Will we start enriching these lines with connector IDs+index name as well so that if concurrent syncs are running (across different search indices), we can tell them apart?

Yes and yes. For a sync job, `sync job ID`, `connector ID` and `index name` will be included in the log.

**Comment by ppf2** [comment]
Yep, those are probably logs from when I tested ahead of the 8.8 release.  Good to hear that the equivalent lines will also be enriched with IDs and name information.  Thx!

**Comment by danajuratoni** [comment]
@wangch079 can we close this issue as done?

**Comment by wangch079** [comment]
Hi @danajuratoni , yes we can close it
