### ISSUE TITLE
Connector errors out when task takes too long

### ISSUE THREAD

**Issue by utibeabasi6** [elastic/connectors-python#799]
## Bug Description
There are two issues i wanted to report actually. The first is that i tried to sync a table with 3 million + rows, but whenever the `_process_idle_jobs` cleanup task runs, it marks the job as idle and errors out because the task takes a while to sync al 3 million rows. I was able to solve this by commenting out `await self._process_idle_jobs()`. 
The second issue is that when the sync completed, i got an error saying `elasticsearch.BadRequestError: BadRequestError(400, 'mapper_parsing_exception', "failed to parse field [indexed_document_volume] of type [integer] in document with id 'nnY9mIcBQYDJddoFjhBJ'. Preview of field's value: '2808782832'")`. Again i solved this by setting `"indexed_document_volume": 0,`

### To Reproduce
Run a sync against a database with over 3 million rows

## Expected behavior
The sync should complete with no errors

## Environment

- OS: docker (kubernetes pod)
- Version [v8.6.0.4](https://github.com/elastic/connectors-python/releases/tag/v8.6.0.4)

**Comment by danajuratoni** [comment]
Seems related to https://github.com/elastic/connectors-python/issues/735
