### ISSUE TITLE
Jira - Advanced Sync Rules

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#874]
https://docs.google.com/document/d/1HUz6YeboywHAueSjwJ7EEE-lD019EsYzQcLCWdL81VY/edit#heading=h.a5t7p873ehh2

### Acceptance criteria
- [x] #945
- [x] #980
- [x] document impact of advanced sync rules on connector configuration and on document indexing
- [x] #1016

**Comment by abhishekjoshi-crest** [comment]
**Updates [18th May - 25th May]**

- Completed with implementation part & addressed comments on PR #946 
    - #945 
- Shared test cases for the same
   - https://docs.google.com/spreadsheets/d/1ymIXNJkFeBFZh0AlT0qJqKCxkzJTR7Kw/edit#gid=2022954419

**Comment by praveen-elastic** [comment]
Updates for [26th May to 7th June]:

- Worked on documentation with some examples illustrating the syntax and use case.
    - Added the impact of Sync Rules on connector indexing and the affect on configurable field `projects`
- Added a tooltip for the configurable field `projects` https://github.com/elastic/connectors-python/pull/1025 and added order in the field `projects`
