### ISSUE TITLE
Confluence - Advanced Sync Rules

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#875]
https://docs.google.com/document/d/1HUz6YeboywHAueSjwJ7EEE-lD019EsYzQcLCWdL81VY/edit#heading=h.aze6y0rxyru8

### Acceptance criteria
- [x] #954
- [x] #979
- [x] document impact of advanced sync rules on connector configuration and on document indexing
- [x] #1015

**Comment by praveen-elastic** [comment]
Sharing last week's progress summary (4th May - 10th May): 

- Studied the google docs shared by Tim for reference.
- Reviewed MySQL code implementation for Advanced Sync Rules
- Explored the Sync Rules in 8.8 deployment
- Started with initial schema definition and explored CQL queries in Confluence

**Comment by praveen-elastic** [comment]
Weekly Updates for [11th May to 17th May]:

- Took a Call with Tim for some guidance for advanced sync rules implementation.
    - Discussed the possible solutions of some questions with Tim.
    - Guidance for allowing sync rules in the index via kibana dev console
- Kicked-off implementation of Sync Rules in Confluence Connector
- Checked the code implementation against various CQL queries
- Started preparing Test Cases

**Comment by praveen-elastic** [comment]
Updates for [18th May to 25th May]:

- Working on documenting basic usage and examples illustrating the syntax for advanced rules
- QAs found some some bugs, fixing them and will raise a PR for Sync rules soon.
- Observed some incoherent behaviour in the API response that we need to document as a limitation for using advanced sync rules: https://jira.atlassian.com/browse/CONFCLOUD-73997

**Comment by praveen-elastic** [comment]
Updates for [26th May to 7th June]:

- Resolved comments and got PR for advanced sync rules merged: https://github.com/elastic/connectors-python/pull/956
- Worked on documentation with some examples illustrating the syntax and use case.
    - Mentioned the limitation of Advanced Sync Rules 
    - Added the impact of Sync Rules on connector indexing and the affect on configurable field `spaces`
- Added a tooltip for the configurable field `spaces` https://github.com/elastic/connectors-python/pull/1025
