### ISSUE TITLE
mapper [size] cannot be changed from type [long] to [text]

### ISSUE THREAD

**Issue by llermaly** [elastic/connectors-python#934]
## Bug Description

I'm seeing the following error in one of my pages: 

[FMWK][12:45:59][WARNING] Retry count: 2 out of 3. Exception: 400, message='Bad Request', url=URL('https://xxxx.sharepoint.com/sites/xxxxx/_api/web/lists/getbytitle('Site%20Pages')/items?$select=Title,CanvasContent1,FileLeafRef&$filter=FileLeafRef+eq+'xxxxxxxx'.aspx'')
[FMWK][12:46:03][ERROR] operation index failed, {'type': 'illegal_argument_exception', 'reason': 'mapper [size] cannot be changed from type [long] to [text]'}

**Comment by seanstory** [comment]
Thanks for reporting, @llermaly.

@danajuratoni for prioritization. I've pre-emptively tagged with 8.9.0, since this looks like a bug in the Sharepoint connector.

It seems that it sometimes is getting a `size` that is non-numeric (or not a number format that Elasticsearch respects as a number)

**Comment by danajuratoni** [comment]
This affects the 8.8 SharePoint connector, and Gustavo found this issue while testing aspx pages. cc: @akanshi-elastic

**Comment by akanshi-elastic** [comment]
Let me check the issue and fix it asap

**Comment by llermaly** [comment]
Hi all, 

It seems like we have 2 issues here, the one related to the mappings, and the one related to the bad request. 

After some crawlings I'm not seeing the mappings one anymore, but I still see the bad request one and I think I know what's going on, the filter part of the URL is not being built correctly:

[FMWK][12:45:59][WARNING] Retry count: 2 out of 3. Exception: 400, message='Bad Request', url=URL('https://xxxx.sharepoint.com/sites/xxxxx/_api/web/lists/getbytitle('Site%20Pages')/items?$select=Title,CanvasContent1,FileLeafRef&$filter=FileLeafRef+eq+**'xxxxxxxx'.aspx''**)

Note those quotes. I tried with postman and I see the same error, then if I change to:

FileLeafRef+eq+**'xxxxxxxx.aspx'**

It works.  I'm not very familiar with the connector but I guess it is because of the file extension in there that is messing the parsing.

**Comment by artem-shelkovnikov** [comment]
Hi @llermaly, can you file each bug individually following the [bug report template](https://github.com/elastic/connectors-python/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=) without removing sections from it?

More details in the ticket means more likelihood of the bug fixed, plus our PRs are attached to issues, so 1 fix per 1 bug process is followed.

**Comment by llermaly** [comment]
Done, I just created:

https://github.com/elastic/connectors-python/issues/939

and 

https://github.com/elastic/connectors-python/issues/940
