### ISSUE TITLE
[Sharepoint] Exception: 400, message='Bad Request'

### ISSUE THREAD

**Issue by llermaly** [elastic/connectors-python#940]
## Bug Description
I'm having a bad request with a specific document URL:

[FMWK][10:51:04][WARNING] Retry count: 3 out of 3. Exception: 400, message='Bad Request', url=URL('https://tenant.sharepoint.com/sites/site/_api/web/lists/getbytitle('Site%20Pages')/items?$select=Title,CanvasContent1,FileLeafRef&$filter=FileLeafRef+eq+'Some-File--Name'.aspx'')

My guess is the ".aspx" in the name is messing with the parsing. I tried in Postman and can reproduce the error, then if I fix the single quote:

'Some-File--Name.aspx'

It works.

### To Reproduce
1. Create sharepoint site with list title with .aspx
2. Run sharepoint crawler
3. See error

## Expected behavior
Object should ingest.

## Screenshots
N/A

## Environment
- Elastic Cloud 8.8
- Sharepoint connector main branch

## Additional context
N/A

**Comment by danajuratoni** [comment]
split from original issue cc: @akanshi-elastic

**Comment by akanshi-elastic** [comment]
Hey @llermaly  , I checked the issue by creating a site page with a name having single/double quote: `Some-File--Name'.aspx` 
And it is throwing 400 bad request on postman as well. I tried to encode the single/double quote but still it's giving 400 error. and it is required to add the quotes around the name of file in url so if we pass single/double quote in between name of file then the url considered it as a closing quote  and throws the error. I also tried to add escape before the quote but that is not working in this case.

So it seems that Sharepoint server is itself unable to parse the single quotes in in their endpoint as we are facing this in the postman too.
if the sharepoint server is not able to process the same request so we can't do much from our side to prevent that.
Let me know your thoughts how do we want to proceed further in this case.
cc: @artem-shelkovnikov

**Comment by llermaly** [comment]
hi @akanshi-elastic , I found another similar than this one: 

`$filter=FileLeafRef+eq+'Some-file-&-name.aspx'`

I could make it work in postman doing 

FileLeafRef+eq+'Some-file-%26-name.aspx'

I was about to create a new issue but looks like the problem is related to the same.

I can make the File--name to work in postman using this notation:

![CleanShot 2023-05-24 at 18 20 45](https://github.com/elastic/connectors-python/assets/8575569/29eaf2c5-956b-417b-916f-d0ed26e3d535)

**Comment by akanshi-elastic** [comment]
Worked on this issue on 23-05-2023 and raised a PR: https://github.com/elastic/connectors-python/pull/968
