### ISSUE TITLE
Dropbox Advanced Sync Rules

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#949]
Similarly to the advanced filtering capabilities added to Jira and Confluence e.g. https://github.com/elastic/connectors-python/issues/874, support customized filtering via advanced sync rules for Dropbox.

### Acceptance criteria
- [ ] add support for advanced sync rules
- [ ] add documentation with several examples illustrating the syntax, how a basic use case works, limitations
- [ ] document impact of advanced sync rules on connector configuration and on document indexing
- [ ] add tooltip on the configurable fields that are ignored when advanced sync rules are used, informing the user about the behavior

**Comment by praveen-elastic** [comment]
Updates [8th June to 15th June]:

Explored the GitHub APIs and documentation for search query parameters
Prepared and shared Sync Rules Object Model and Schema as a document: https://docs.google.com/document/d/1bNEvbxJyW_MAmZEcNe9Y8gBv6PbnzbVEhLU7HnEKflg/edit

**Comment by praveen-elastic** [comment]
Updates [8th June to 15th June]:

Explored the Dropbox APIs and documentation for search query parameters
Prepared and shared Sync Rules Object Model and Schema as a document: https://docs.google.com/document/d/1bNEvbxJyW_MAmZEcNe9Y8gBv6PbnzbVEhLU7HnEKflg/edit
