### ISSUE TITLE
GitHub Advanced Sync Rules

### ISSUE THREAD

**Issue by danajuratoni** [elastic/connectors-python#950]
Similarly to the advanced filtering capabilities added to Jira and Confluence e.g. https://github.com/elastic/connectors-python/issues/874, support customized filtering via advanced sync rules for GitHub.

### Acceptance criteria
- [x] add support for advanced sync rules
- [x] add documentation with several examples illustrating the syntax, how a basic use case works, limitations
- [x] document impact of advanced sync rules on connector configuration and on document indexing
- [x] add tooltip on the configurable fields that are ignored when advanced sync rules are used, informing the user about the behavior

**Comment by abhishekjoshi-crest** [comment]
All tasks of advanced sync rules was completed. Hence, closing this issue
